# Lab 2: Numpy, Pandas and Matplotlib

## 1. Numpy

1. What are the differences between Numpy's array and Python's list?

> <br />
> 1. 
>    - Numpy can create array faster (than python create list) with efficient and manipulating numerical data inside them. <br /><br />
> 2. <br />
>    - Python's list can contain different data types in same list `called heterogeneous`. <br />
>    - Numpy's array elements must have the same data type `called homogeneous`. <br /><br />
> 3. 
>    - Numpy's array use less memory (than python's list) to store data and it provides a mechanism of specifying the data types. <br /><br />
> 4. 
>    - Numpy arrays have a `fixed size` at creation, unlike Python lists (can grow dynamically), so changing the size will create a new array and delete the original. <br /><br />

2. What are the advantages of using Numpy over Python's list for numerical computing?

> <br />
> Numpy support some specific scientific features <br /><br />
>   - linear algebra <br />
>   - vectorized operations <br /><br />
> which python cannot support these features. <br />
> <br />

3. Give 4 example on how Numpy's ndarray can be created.

In [2]:
import numpy as np

# Convert from Python's list
arr1 = np.array(['x', 'y', 'z'])
print(type(arr1))
arr1

<class 'numpy.ndarray'>


array(['x', 'y', 'z'], dtype='<U1')

In [3]:
# generate by np.zeros() : all element has zero as initial value
arr2 = np.zeros((4, 3))
print(type(arr2))
arr2

<class 'numpy.ndarray'>


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# generate by np.eye() : identity matrix
arr3 = np.eye(3)
print(type(arr3))
arr3

<class 'numpy.ndarray'>


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# generate by np.linspace(start, stop, step)
arr4 = np.linspace(1, 9, 5)
print(type(arr4))
arr4

<class 'numpy.ndarray'>


array([1., 3., 5., 7., 9.])

4. Give an example of Numpy's functions that change the shape of ndarray? Also provide
short description of each function.

In [34]:
# initial array
arr_bf = np.arange(4)
print(arr_bf)
print("arr_bf shape : ", arr_bf.shape, "\n")

# use reshape(row, col) : C-like index ordering
arr_reshape_c = np.reshape(arr_bf, (2, 2))
print(arr_reshape_c)
print("arr_reshape_c shape : ", arr_reshape_c.shape, "\n")

# use reshape(row, col) : Fortran-like index ordering
arr_reshape_f = np.reshape(arr_bf, (2, 2), order='F')
print(arr_reshape_f) 
print("arr_reshape_f shape : ", arr_reshape_f.shape, "\n")

# use transpose : row ↔ column (with 2D-array)
arr_t = np.transpose([arr_bf])
print(arr_t) 
print("arr_t shape : ", arr_t.shape)


[0 1 2 3]
arr_bf shape :  (4,) 

[[0 1]
 [2 3]]
arr_reshape_c shape :  (2, 2) 

[[0 2]
 [1 3]]
arr_reshape_f shape :  (2, 2) 

[[0]
 [1]
 [2]
 [3]]
arr_t shape :  (4, 1)


## 2. Pandas

In [36]:
import pandas as pd

1. What are two main data structure of Pandas? How are they differs and when should each be
used?

> <br />
> 1. Series <br />
>   - one-dimensional labeled array, can holding any data type <br />
>   - data inside can bring from `ndarray`, `scalar value`, or `dictionary` <br />
>   - should use when having 1D array <br /><br />
> 2. Dataframe <br />
>   - two-dimensional labeled structure <br />
>   - data inside can bring from `1D : ndarrays, lists, dicts, Series`, `2D numpy's array`, or `another Dataframe` <br />
>   - should use for managing `spreadsheet`, `SQL table`, or any 2D table <br />
> <br />

2. Give an example on how Pandas DataFrame can be created.

In [44]:
# data : empty
df1 = pd.DataFrame()
print("* Empty Dataframe")
print(df1, "\n")

# data : dictionary of ndarrays
df2 = pd.DataFrame({
    'a' : np.arange(4),
    'b' : np.zeros(4)
})
print("* Dataframe from Dictionary of ndarrays")
print(df2)

* Empty Dataframe
Empty DataFrame
Columns: []
Index: [] 

* Dataframe from Dictionary of ndarrays
   a    b
0  0  0.0
1  1  0.0
2  2  0.0
3  3  0.0


3. What is the difference between df.loc and df.iloc in data selection?

> - df.loc : choose rows & columns by specific `label`
> - df.iloc : choose rowa & columns at specific `index position`

4. Why is it necessary to explore the cause of missing data? Can't we just drop it?

5. What is the difference between df.apply and df.transform ?

6. Give an example of Pandas functions that transform the shape of dataframe.

7. From superstore dataset, prepare the dataset to answer following question. Provide explanation on each step as well.

In [47]:
data_order = pd.read_csv(r'../public/data/superstore_order.csv')
data_people = pd.read_csv(r'../public/data/superstore_people.csv')
data_return = pd.read_csv(r'../public/data/superstore_return.csv')

<pre>       1. Observe the weekly sales of each product </pre>

In [61]:
df_order = pd.DataFrame(data_order)
df_week_order = pd.DataFrame(data_order)
df_week_order['Order Date'] = pd.to_datetime(df_week_order['Order Date']) - pd.to_timedelta(7, unit='d')
print(df_week_order.groupby([pd.Grouper(key='Order Date', freq='W')])['Product ID'].value_counts())
print()
# print(df_order[ ['Order Date', 'Product ID']].value_counts())

Order Date  Product ID     
2013-11-03  FUR-CH-10000863    1
            FUR-CH-10001270    1
            FUR-CH-10004063    1
            FUR-FU-10001095    1
            FUR-TA-10001866    1
                              ..
2017-10-29  TEC-PH-10000347    1
            TEC-PH-10000576    1
            TEC-PH-10002563    1
            TEC-PH-10002890    1
            TEC-PH-10004774    1
Name: Product ID, Length: 8760, dtype: int64



<pre>       2. Find out which customers have returned products at least once </pre>

<pre>       3. Sales to profit ratio of each subcategory </pre>

<pre>       4. Orders that takes more than 5 days to prepare for shipping </pre>

<pre>       5. Shipping method distribution on each state </pre>

## 3. Matplotlib

From superstore dataset, plot visualization to answer following question using appropriate visual element.

1. Number of customer who has returned product atleast once and those who never returned
products.

2. Weekly sales of each product category.

3. Distribution of how many times a customer purchased product from this store.

4. Comparative statistical distribution of profit per sale unit between each sub-category in
furniture category.